services:
  db:
    image: postgres:15
    container_name: event_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: event_nest_app
    restart: always
    env_file: ../.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      # Mount code local -> container (auto reload)
      - .:/usr/src/app
      # Giữ lại node_modules trong container
      - /usr/src/app/node_modules
    command: sh -c "sleep 5 && npm run migration:run && npm run seed:run && npm run start:prod"

volumes:
  postgres_data:
